wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.2
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712136218.841811
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 23
      4: 3.8.2
      5: 0.16.3
      8:
      - 5
      13: darwin-x86_64
